### ISSUE TITLE
Wrong OpenSSL API usage to verify X509 chain

### ISSUE THREAD

**Issue by kroeckx** [SWI-Prolog/packages-ssl#158] opened 2020-10-25 12:27 UTC
With the new OpenSSL 1.1.1h, we're seeing testsuite errors in Debian. For a log see https://ci.debian.net/data/autopkgtest/testing/amd64/s/swi-prolog/7715788/log.gz

The problem seems to be caused by a change in behaviour of the X509_check_issued() function. It had checks in it that didn't belong there, which now seem to cause test suite failures.

But the real problem is that you seem to be doing your own chain validation using X509_check_issued() instead of using X509_verify_cert(), that properly validates the whole chain, including checks that you can't do using X509_check_issued(). If you use X509_verify_cert(), you should not just pass it 2 certificates each time, you should pass it the certificate you want to verify, the trusted and untrusted certificates you have, and it will check everything that needs to be checked.

**Comment by kroeckx** [comment] 2020-10-25 13:11
Looking closer, it seems X509_verify_cert() is also used, and that X509_check_issued() change in behaviour is probably unrelated.
I don't understand enough for the swi-prolog code to understand what is going on.

**Comment by JanWielemaker** [comment] 2020-10-25 18:26
Checking with @thetrime.   I'm not much of an OpenSSL expert, hopefully the two of you can fill in the blanks.

**Comment by JanWielemaker** [comment] 2020-10-26 08:31
@kroeckx Note that the failed tests verify the callback on the certificate verification hook.   In the most recent version of the SSL package we changed testing how this hook is called to a _set_ rather than a _list_ as the pre-1.1.1h versions call the hook often multiple times with the same arguments and there seems to be a difference in the order in which the hook is called with different arguments.   So, the latest version of the SSL package passes the tests with 1.1.1h.   If I understand you correctly, possibly for the wrong reasons though.   I'm awaiting @thetrime's reply on this.

I've prepared SWI-Prolog 8.2.2, cherry-picking all fully compatible bug fixes from the development branch.   I hold its distribution until this is resolved.

**Comment by kroeckx** [comment] 2020-10-26 09:19
I've been going over https://github.com/openssl/openssl/commit/e2590c3a162eb118c36b09c2168164283aa099b4, which appears to be the commit that cause the test to fail, but I currently don't see how it has an effect.

**Comment by JanWielemaker** [comment] 2020-10-26 09:46
I'm afraid my knowledge about certificate handling in general is restricted to a high-level view and my knowledge about OpenSSL is pretty limited as well.   My contribution to this is pretty much limited to some Prolog interface details and packaging.

**Comment by JanWielemaker** [comment] 2020-10-27 08:20
I'm looking into this.   First of all, X509_check_issued() is used to implement the Prolog predicate verify_certificate_issuer/2, which is a predicate provided by the Prolog SSL binding but not used as part of the normal checking procedure.  I've put a gdb breakpoint in the callback we are verifying on these failed tests to see how the callback is called.  This gives

```
#0  pl_cert_verify_hook (config=0x5555564126c0, cert=0x5555563874a0, 
    ctx=0x555556452c00, error=0x7ffff67b146c "verified", error_unknown=0)
    at ../packages/ssl/ssl4pl.c:1662
#1  0x00007ffff67aa047 in ssl_cb_cert_verify (preverify_ok=1, 
    ctx=0x555556452c00) at ../packages/ssl/ssl4pl.c:2252
#2  0x00007ffff665f1c0 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#3  0x00007ffff6660de6 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#4  0x00007ffff666167c in X509_verify_cert ()
   from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#5  0x00007ffff6407568 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#6  0x00007ffff6429029 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#7  0x00007ffff642b755 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#8  0x00007ffff642507d in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#9  0x00007ffff6410d58 in SSL_do_handshake ()
   from /lib/x86_64-linux-gnu/libssl.so.1.1
#10 0x00007ffff67aba72 in ssl_ssl_bio (config=0x5555564126c0, 
    sread=0x555556452800, swrite=0x555556452900, instancep=0x7fffffffa1c0)
    at ../packages/ssl/ssl4pl.c:3148
#11 0x00007ffff67ad6d5 in pl_ssl_negotiate (config=585, org_in=586, 
```

This seems correct.  X509_verify_cert() is the used verification method and this calls the hook reporting several times during the verification process.   I have the impression OpenSSL has changed the order of the verification steps and avoids some work duplication.  If this is correct, we should be fine.

Note that without  the callback, we just have the plain behavior of X509_verify_cert().  With we get more detailed information and can decide to accept a certificate despite certain issues.

**Comment by dogsleg** [comment] 2020-10-29 07:51
I tested swi-prolog 8.2.2 with openssl 1.1.1h, and seems the issue is resolved. I just uploaded 8.2.2 to the Debian archive.

**Comment by JanWielemaker** [comment] 2020-10-29 07:53
Thanks for that!   Moving to 8.2.2 should resolve quite a few issues.

**Closed by JanWielemaker** 2020-10-29 07:53 UTC
